# prometheus.yml
global:
  scrape_interval: 30s
  external_labels:
    monitor: 'pihole'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'hubitat'
    static_configs:
      - targets: ['hubitat2prom:8080']
